apiVersion: 1

#list of datasources to insert/update
datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: db.:5353
    database: test
    user: postgres
    secureJsonData:
      password: 'example'
    jsonData:
      sslmode: 'disable'